"""
Quantize trained float32 RNN weights to int8 and emit a C header
that the ESP32 firmware compiles straight into flash.

    W_approx = int8_weight * scale
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def quantize_int8(w: np.ndarray):
    w = np.asarray(w, dtype=np.float32).ravel()
    max_abs = float(np.max(np.abs(w))) if w.size else 1.0
    scale = max_abs / 127.0 if max_abs > 0 else 1.0
    q = np.clip(np.round(w / scale), -127, 127).astype(np.int8)
    return q, scale


def c_array(name: str, q: np.ndarray, cols: int = 16) -> str:
    vals = [str(int(v)) for v in q]
    lines = []
    for i in range(0, len(vals), cols):
        lines.append("    " + ", ".join(vals[i : i + cols]) + ",")
    body = "\n".join(lines).rstrip(",")
    return f"const int8_t {name}[{len(q)}] PROGMEM = {{\n{body}\n}};\n"


def emit_header(npz_path: Path, out_path: Path) -> None:
    data = np.load(npz_path, allow_pickle=True)
    Wxh, Whh, Why = data["Wxh"], data["Whh"], data["Why"]
    bh, by = data["bh"], data["by"]
    raw = data["vocab"]
    try:
        vocab = str(raw.item())
    except (AttributeError, ValueError):
        vocab = str(raw)
    H = int(data["hidden_size"])
    V = len(vocab)

    if Wxh.shape != (H, V) or Whh.shape != (H, H) or Why.shape != (V, H):
        raise SystemExit(f"Unexpected shapes: Wxh={Wxh.shape} Whh={Whh.shape} Why={Why.shape}")

    q_wxh, s_wxh = quantize_int8(Wxh)
    q_whh, s_whh = quantize_int8(Whh)
    q_why, s_why = quantize_int8(Why)
    q_bh, s_bh = quantize_int8(bh)
    q_by, s_by = quantize_int8(by)

    n_params = q_wxh.size + q_whh.size + q_why.size + q_bh.size + q_by.size
    vocab_c = vocab.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    header = f"""\
#pragma once
// Auto-generated by train/export.py — do not edit by hand.
// Tiny char-RNN: h = tanh(Wxh x + Whh h + bh),  z = Why h + by

#include <stdint.h>
#include <pgmspace.h>

#define HIDDEN_SIZE {H}
#define VOCAB_SIZE  {V}
#define N_PARAMS    {n_params}

static const char VOCAB[VOCAB_SIZE + 1] = "{vocab_c}";

#define WXH_SCALE {s_wxh:.9e}f
#define WHH_SCALE {s_whh:.9e}f
#define WHY_SCALE {s_why:.9e}f
#define BH_SCALE  {s_bh:.9e}f
#define BY_SCALE  {s_by:.9e}f

{c_array("WXH", q_wxh)}
{c_array("WHH", q_whh)}
{c_array("WHY", q_why)}
{c_array("BH", q_bh)}
{c_array("BY", q_by)}
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8")
    print(f"exported {n_params} int8 weights -> {out_path}")
    print(f"  Wxh scale={s_wxh:.6f}  Whh scale={s_whh:.6f}  Why scale={s_why:.6f}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--npz", type=Path, default=Path(__file__).parent / "checkpoints" / "rnn.npz")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).parent.parent / "firmware" / "02_TinyLM" / "model_weights.h",
    )
    args = parser.parse_args()
    if not args.npz.exists():
        raise SystemExit(f"Missing {args.npz}. Run train.py first.")
    emit_header(args.npz, args.out)


if __name__ == "__main__":
    main()
